package GUI;
import dormsignout.Student;
import dormsignout.SignOutInfo;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.Calendar;
import javax.swing.JComponent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author frank
 */
public class SignOutPanel extends javax.swing.JPanel {

    private MainFrame main;
    private String teacherApproval;
    private String goingWith;
    private String timeBack;
    private String timeLeaving;
    private String howToGetThere;
    private String whereGoing;
    private String dorm;
    private String firstName;
    private String lastName;
    private String studentID;
    /**
     * Creates new form SignOutPanel
     */
    public SignOutPanel(MainFrame m) {
        main = m;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        backHourDrop = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        backMinuteDrop = new javax.swing.JComboBox<>();
        howLabel = new javax.swing.JLabel();
        howDropBox = new javax.swing.JComboBox<>();
        backAmDrop = new javax.swing.JComboBox<>();
        teacherApproveLabel = new javax.swing.JLabel();
        whoLabel = new javax.swing.JLabel();
        whichTeacherText = new javax.swing.JTextField();
        travelWithText = new javax.swing.JTextField();
        whereLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        whereText = new javax.swing.JTextField();
        timeLeavingLabel = new javax.swing.JLabel();
        leavingHourDrop = new javax.swing.JComboBox<>();
        leavingMinuteDrop = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        leavingAmDrop = new javax.swing.JComboBox<>();
        timeBackLabel = new javax.swing.JLabel();
        dormLabel = new javax.swing.JLabel();
        dormDrop = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        studentIDText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        dateCombo = new javax.swing.JComboBox<>();

        jToolBar1.setRollover(true);

        backHourDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel10.setText(":");

        backMinuteDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        howLabel.setText("How are you getting there:");

        howDropBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taxi", "Parents", "Friends", "Teachers", "Drive" }));
        howDropBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howDropBoxActionPerformed(evt);
            }
        });

        backAmDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        teacherApproveLabel.setText("Which teacher approved: ");

        whoLabel.setText("Who are you going with: ");

        whichTeacherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whichTeacherTextActionPerformed(evt);
            }
        });

        travelWithText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelWithTextActionPerformed(evt);
            }
        });

        whereLabel.setText("Where are you going: ");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        timeLeavingLabel.setText("When are you leaving: ");

        leavingHourDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        leavingHourDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavingHourDropActionPerformed(evt);
            }
        });

        leavingMinuteDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jLabel8.setText(":");

        leavingAmDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        leavingAmDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavingAmDropActionPerformed(evt);
            }
        });

        timeBackLabel.setText("When are you going to be back: ");

        dormLabel.setText("Which dorm are you from: ");

        dormDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlass", "Ferry", "Field", "Warner", "Mac" }));

        jLabel1.setText("Signout Information");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name: ");

        jLabel4.setText("Student ID:");

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dateLabel.setText("Date:");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        dateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dormLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dormDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLeavingLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(leavingHourDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leavingMinuteDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(leavingAmDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(whoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(whereText, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(travelWithText))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teacherApproveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(whichTeacherText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(whereLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(howLabel)
                                .addGap(18, 18, 18)
                                .addComponent(howDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(14, 14, 14)
                                    .addComponent(firstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(lastNameText))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dateLabel)
                                    .addGap(53, 53, 53)
                                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(201, 201, 201)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeBackLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backHourDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10)
                                .addGap(5, 5, 5)
                                .addComponent(backMinuteDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backAmDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(howDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherApproveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whichTeacherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whoLabel)
                    .addComponent(travelWithText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whereLabel)
                    .addComponent(whereText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leavingAmDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLeavingLabel)
                    .addComponent(leavingHourDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(leavingMinuteDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeBackLabel)
                    .addComponent(backHourDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backMinuteDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(backAmDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dormLabel)
                    .addComponent(dormDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void howDropBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howDropBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_howDropBoxActionPerformed

    private void leavingHourDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavingHourDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leavingHourDropActionPerformed

    private void leavingAmDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavingAmDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leavingAmDropActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try{
            teacherApproval = whichTeacherText.getText();
            goingWith = travelWithText.getText();
            whereGoing = whereText.getText();
            dorm = dormDrop.getSelectedItem().toString();
            timeLeaving = leavingHourDrop.getSelectedItem().toString() + ": " + leavingMinuteDrop.getSelectedItem().toString() + " " + leavingAmDrop.getSelectedItem().toString();
            timeBack = backHourDrop.getSelectedItem().toString() + ": " + backMinuteDrop.getSelectedItem().toString() + " " + backAmDrop.getSelectedItem().toString();
            howToGetThere = howDropBox.getSelectedItem().toString();
            firstName = firstNameText.getText();
            lastName = lastNameText.getText();
            studentID = studentIDText.getText();
            Student cur = new Student(firstName, lastName, studentID, dorm);
            //int number = Integer.parseInt(numberTextField.getText());
            //String position = positionTextField.getText();
            Calendar cal = Calendar.getInstance();
            //String date = cal.toString();
            String date = monthCombo.getSelectedItem().toString() + dateCombo.getSelectedItem().toString();
            main.addStudent(goingWith, whereGoing, teacherApproval, timeLeaving, timeBack, "No", date, cur);
            main.refreshPanels();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error trying to add athlete: " + ex,
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        ((JDialog) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ((JDialog) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void travelWithTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelWithTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travelWithTextActionPerformed

    private void whichTeacherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whichTeacherTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whichTeacherTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> backAmDrop;
    private javax.swing.JComboBox<String> backHourDrop;
    private javax.swing.JComboBox<String> backMinuteDrop;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> dormDrop;
    private javax.swing.JLabel dormLabel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JComboBox<String> howDropBox;
    private javax.swing.JLabel howLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JComboBox<String> leavingAmDrop;
    private javax.swing.JComboBox<String> leavingHourDrop;
    private javax.swing.JComboBox<String> leavingMinuteDrop;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JTextField studentIDText;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel teacherApproveLabel;
    private javax.swing.JLabel timeBackLabel;
    private javax.swing.JLabel timeLeavingLabel;
    private javax.swing.JTextField travelWithText;
    private javax.swing.JLabel whereLabel;
    private javax.swing.JTextField whereText;
    private javax.swing.JTextField whichTeacherText;
    private javax.swing.JLabel whoLabel;
    // End of variables declaration//GEN-END:variables
}
